### ISSUE TITLE
Neo4j springboot migration fail using version 5.x

### ISSUE THREAD

**Issue by rohitbatta** [liquibase/liquibase-neo4j#281]
I am trying to use neo4j liquibase (4.17.1) using spring boot. But, while starting up the service, i am getting following exception for execution of liquibase change log. 

`2022-11-21 13:32:22.761  WARN 5812 --- [           main] o.n.jdbc.bolt.BoltNeo4jDatabaseMetaData  : Could not retrieve DBMS functions:
org.neo4j.driver.exceptions.ClientException: There is no procedure with the name `dbms.functions` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
`

`build.gradle` is having following configuration. 
```  
    runtimeOnly 'org.springframework.boot:spring-boot-starter-jdbc'
    runtimeOnly 'org.liquibase:liquibase-core:4.17.2'
    runtimeOnly 'org.liquibase.ext:liquibase-neo4j:4.17.1'
```

Version `4.17.2` is not available on maven-central repository. But, I have seen that `4.17.2` is released in this repository already. 

After doing some readup, i have found that there are some breaking changes in neo4j4.4 to neo4j5.0 . 
[Breaking changes neo4j](https://neo4j.com/docs/upgrade-migration-guide/current/version-5/migration/breaking-changes/#_removals) 

`dbms.functions` has been renamed to `SHOW FUNCTIONS`

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock despite no lock currently stored
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at com.proactis.core.organisation.OrganisationServiceApplication.main(OrganisationServiceApplication.java:12) ~[main/:na]
Caused by: liquibase.exception.LockException: Could not acquire change log lock despite no lock currently stored
	at liquibase.ext.neo4j.lockservice.Neo4jLockService.waitForLock(Neo4jLockService.java:73) ~[liquibase-neo4j-4.17.1.jar:4.17.1]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:239) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:2447) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:236) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:221) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:328) ~[liquibase-core-4.17.2.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:283) ~[liquibase-core-4.17.2.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.23.jar:5.3.23]
	... 18 common frames omitted
Caused by: java.util.concurrent.ExecutionException: liquibase.exception.LockException: Could not acquire lock
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[na:na]
	at liquibase.ext.neo4j.lockservice.ConditionCheckScheduler.scheduleCheckWithFixedDelay(ConditionCheckScheduler.java:38) ~[liquibase-neo4j-4.17.1.jar:4.17.1]
	at liquibase.ext.neo4j.lockservice.Neo4jLockService.waitForLock(Neo4jLockService.java:57) ~[liquibase-neo4j-4.17.1.jar:4.17.1]
	... 30 common frames omitted
Caused by: liquibase.exception.LockException: Could not acquire lock
	at liquibase.ext.neo4j.lockservice.Neo4jLockService.acquireLock(Neo4jLockService.java:129) ~[liquibase-neo4j-4.17.1.jar:4.17.1]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: liquibase.exception.DatabaseException: Unique constraint creation for (n:__LiquibaseLock {lockedBy}) aborted: Neo4j version 5.1.0 is not supported
	at liquibase.ext.neo4j.database.Neo4jDatabase.createUniqueConstraint(Neo4jDatabase.java:109) ~[liquibase-neo4j-4.17.1.jar:4.17.1]
	at liquibase.ext.neo4j.lockservice.Neo4jLockService.init(Neo4jLockService.java:135) ~[liquibase-neo4j-4.17.1.jar:4.17.1]
	at liquibase.ext.neo4j.lockservice.Neo4jLockService.acquireLock(Neo4jLockService.java:109) ~[liquibase-neo4j-4.17.1.jar:4.17.1]
	... 5 common frames omitted

Caused by: liquibase.exception.LockException: Could not acquire change log lock despite no lock currently stored

Caused by: java.util.concurrent.ExecutionException: liquibase.exception.LockException: Could not acquire lock

Caused by: liquibase.exception.LockException: Could not acquire lock

Caused by: liquibase.exception.DatabaseException: Unique constraint creation for (n:__LiquibaseLock {lockedBy}) aborted: Neo4j version 5.1.0 is not supported```

**Comment by fbiville** [comment]
Hello, as for https://github.com/liquibase/liquibase-neo4j/issues/282, the cause is the same: the [underlying JDBC connector](https://github.com/neo4j-contrib/neo4j-jdbc) is not ready yet for v5, a release for Neo4j 5 support will land soon.

**Comment by fbiville** [comment]
In the mean time, you can try building the neo4j-jdbc-bolt JAR from sources and see if that works for you:

git clone https://github.com/neo4j-contrib/neo4j-jdbc.git
mvn install --file neo4j-jdbc/pom.xml --also-make --projects neo4j-jdbc-bolt -DskipTests

Then add to your POM:

<dependency>
        <groupId>org.neo4j</groupId>
        <artifactId>neo4j-jdbc-bolt</artifactId>
        <version>5.1.0</version>
</dependency>

Once you're done, do not forget to remove the dependency from your local cache (rm -r ~/.m2/repository/org/neo4j/neo4j-jdbc-bolt/5.1.0)

**Comment by fbiville** [comment]
Alternatively @rohitbatta, can you try https://github.com/liquibase/liquibase-neo4j/releases/tag/liquibase-neo4j-jdbc-alpha-01 and report back?

**Comment by rohitbatta** [comment]
@fbiville Sure, I will check with pre-release and test it with my use-case and will provide a feedback. Thanks.

**Comment by fbiville** [comment]
@rohitbatta have you had a chance to try the pre-release?

**Comment by rohitbatta** [comment]
|Hi @fbiville ,

I have tested the new version `4.19.0` locally and i found that following `driver` classes are not found anymore. 

`org.neo4j.jdbc.boltrouting.BoltRoutingNeo4jDriver` and `org.neo4j.jdbc.bolt.BoltDriver`

**Exception:**
`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: org.neo4j.jdbc.bolt.BoltDriver

Caused by: java.lang.IllegalStateException: Cannot load driver class: org.neo4j.jdbc.bolt.BoltDriver`

If I include following dependency to have `jdbc-bolt` driver.  `implementation 'org.neo4j:neo4j-jdbc-bolt:5.0.0'`

This result in following exception. 

`The called method's class, org.neo4j.driver.Values, is available from the following locations:`

    jar:file:/.../.gradle/caches/modules-2/files-2.1/org.neo4j/neo4j-jdbc-bolt/5.0.0/4077de6e53f6e6d3eb110dcf7251a8eeb734152e/neo4j-jdbc-bolt-5.0.0.jar!/org/neo4j/driver/Values.class
    jar:file:/.../.gradle/caches/modules-2/files-2.1/org.neo4j.driver/neo4j-java-driver/4.4.11/b854f8e7f0f2ab253fb4f98d1cdf3129eaba5696/neo4j-java-driver-4.4.11.jar!/org/neo4j/driver/Values.class

`The called method's class hierarchy was loaded from the following locations:`

    org.neo4j.driver.Values: file:/.../.gradle/caches/modules-2/files-2.1/org.neo4j/neo4j-jdbc-bolt/5.0.0/4077de6e53f6e6d3eb110dcf7251a8eeb734152e/neo4j-jdbc-bolt-5.0.0.jar

`Action:`
`Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.data.neo4j.core.convert.CypherTypes and org.neo4j.driver.Values`

**Comment by rohitbatta** [comment]
Hello @fbiville ,

If i include `implementation 'org.neo4j:neo4j-jdbc-driver:4.0.9'` this dependency, then it seems to me working for use-case. 

Following, I have in my build.gradle to make it working. 
```// for liquibase execution
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.liquibase:liquibase-core:4.19.0'
    implementation 'org.liquibase.ext:liquibase-neo4j:4.19.0'
    implementation 'org.neo4j:neo4j-jdbc-driver:4.0.9'```

**Comment by rohitbatta** [comment]
@fbiville , thanks for your response. I will check the reference documentation and will provide you an update soon.
