### ISSUE TITLE
Liquibase Neo4j Docker: Incompatibility with 4.23.0

### ISSUE THREAD

**Issue by rohitbatta** [liquibase/liquibase-neo4j#426]
I have created docker image using base image as 
```
FROM liquibase/liquibase
RUN lpm add liquibase-neo4j --global
COPY ./neo4j-java-driver.4.4.11.jar /liquibase/lib/neo4j-java-driver.4.4.11.jar
COPY ./reactive-streams-1.0.4.jar /liquibase/lib/reactive-streams-1.0.4.jar
CMD ["sh", "-c", "docker-entrypoint.sh"]
```
Now, when i do some testing using liquibase commands. 
Following commands are working fine. 

- `liquibase history`
- `liquibase status`

But, when i try to run this `liquibase updateSQL` on docker terminal. 
Then following error appears. 

```
Liquibase Version: 4.23.0
Liquibase Open Source 4.23.0 by Liquibase

Unexpected error running Liquibase: Receiver class liquibase.ext.neo4j.changelog.Neo4jChangelogHistoryService does not define or inherit an implementation of the resolved method 'abstract boolean isDatabaseChecksumsCompatible()' of interface liquibase.changelog.ChangeLogHistoryService
```

All required env variables are already set to the container. 

I have verified in mentioned class and indeed that method is not implemented. 

Logs from docker container. 
```
[2023-07-25 12:39:32] FINE [liquibase.servicelocator] Loaded liquibase.changelog.ChangeLogHistoryService instance liquibase.changelog.StandardChangeLogHistoryService
[2023-07-25 12:39:32] FINE [liquibase.servicelocator] Loaded liquibase.changelog.ChangeLogHistoryService instance liquibase.ext.neo4j.changelog.Neo4jChangelogHistoryService
[2023-07-25 12:39:32] FINE [liquibase.command] Executing internal command changeExecListener
[2023-07-25 12:39:32] FINE [liquibase.command] Executing internal command updateSql migrateSql
[2023-07-25 12:39:32] INFO [liquibase.command] Command execution complete
[2023-07-25 12:39:32] SEVERE [liquibase.integration] Receiver class liquibase.ext.neo4j.changelog.Neo4jChangelogHistoryService does not define or inherit an implementation of the resolved method 'abstract boolean isDatabaseChecksumsCompatible()' of interface liquibase.changelog.ChangeLogHistoryService.
java.lang.AbstractMethodError: Receiver class liquibase.ext.neo4j.changelog.Neo4jChangelogHistoryService does not define or inherit an implementation of the resolved method 'abstract boolean isDatabaseChecksumsCompatible()' of interface liquibase.changelog.ChangeLogHistoryService.
        at liquibase.command.core.AbstractUpdateCommandStep.isUpToDateFastCheck(AbstractUpdateCommandStep.java:194)
        at liquibase.command.core.AbstractUpdateCommandStep.isUpToDate(AbstractUpdateCommandStep.java:249)
        at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:60)
        at liquibase.command.core.UpdateSqlCommandStep.run(UpdateSqlCommandStep.java:60)
        at liquibase.command.CommandScope.execute(CommandScope.java:213)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:381)
        at liquibase.Scope.child(Scope.java:206)
        at liquibase.Scope.child(Scope.java:182)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:356)
        at liquibase.Scope.child(Scope.java:206)
        at liquibase.Scope.child(Scope.java:182)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:354)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:94)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)


Unexpected error running Liquibase: Receiver class liquibase.ext.neo4j.changelog.Neo4jChangelogHistoryService does not define or inherit an implementation of the resolved method 'abstract boolean isDatabaseChecksumsCompatible()' of interface liquibase.changelog.ChangeLogHistoryService.

java.lang.AbstractMethodError: Receiver class liquibase.ext.neo4j.changelog.Neo4jChangelogHistoryService does not define or inherit an implementation of the resolved method 'abstract boolean isDatabaseChecksumsCompatible()' of interface liquibase.changelog.ChangeLogHistoryService.
        at liquibase.command.core.AbstractUpdateCommandStep.isUpToDateFastCheck(AbstractUpdateCommandStep.java:194)
        at liquibase.command.core.AbstractUpdateCommandStep.isUpToDate(AbstractUpdateCommandStep.java:249)
        at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:60)
        at liquibase.command.core.UpdateSqlCommandStep.run(UpdateSqlCommandStep.java:60)
        at liquibase.command.CommandScope.execute(CommandScope.java:213)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$2(LiquibaseCommandLine.java:381)
        at liquibase.Scope.child(Scope.java:206)
        at liquibase.Scope.child(Scope.java:182)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:356)
        at liquibase.Scope.child(Scope.java:206)
        at liquibase.Scope.child(Scope.java:182)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:354)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:94)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
```

Am I missing something here?

**Comment by fbiville** [comment]
Hello, Liquibase core 4.23.0 introduces some breaking changes that Liquibase Neo4j cannot support at the moment.
I'm waiting for Liquibase core 4.23.1 to push a release for the Neo4j extension.

You need to downgrade to Liquibase 4.22 or earlier for now, I'm afraid.

**Comment by rohitbatta** [comment]
@fbiville , thanks, Indeed it is working with old base image`liquibase/liquibase:4.21.1-alpine`. I have validated that and currently using that one. 
If you need, then we could keep this ticket open or you can close it if it has been already raised earlier. 👍

**Comment by fbiville** [comment]
4.23.1 release is underway.

**Comment by rohitbatta** [comment]
Just tested, docker image version 4.23.1 is still not correct and pointed to 4.23.0

**Comment by fbiville** [comment]
@rohitbatta forwarded to the core team, I'll let you know of any updates.
