### ISSUE TITLE
Bump JDK baseline

### ISSUE THREAD

**Issue by fbiville** [liquibase/liquibase-neo4j#52]
The next JDBC driver release will be built against JDK 11. (EDIT: this is version 4.0.2 released on August 3rd, 2021).

This currently causes issue with this plugin, like in this example: 
```java
liquibase.exception.LiquibaseException: Unexpected error running Liquibase: org/neo4j/jdbc/bolt/BoltDriver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at liquibase.integration.commandline.Main$1.run(Main.java:444)
	at liquibase.integration.commandline.Main$1.run(Main.java:222)
	at liquibase.Scope.child(Scope.java:175)
	at liquibase.Scope.child(Scope.java:151)
	at liquibase.integration.commandline.Main.run(Main.java:222)
	at liquibase.ext.neo4j.Neo4jPluginTest.runs migrations(Neo4jPluginTest.groovy:116)
Caused by: java.lang.UnsupportedClassVersionError: org/neo4j/jdbc/bolt/BoltDriver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[...]
```
Indeed, the Neo4j plugin has a JDK 8 base line (and so does Liquibase Core).
Would it be a big problem to bump to JDK 11?

**Comment by fbiville** [comment]
The JDBC driver has been reworked so it can adopt again a JDK 1.8 baseline (the only dependency was Neo4j test harness... tests now rely on TestContainers).
